local potionsTable = {
    {Name = "Kooldown-Aid", potId = 36723, itemNeed = {8192, 5894, 5922}, itemQuantity = {1, 10, 10}, costGp = 100000, questNeed = "The Inquisition Quest", questStorage = 100386, storageId = 3, levelNeed = 120, alchemistExp = 0, alchemistLevel = 4, potionsClass = 1, potionDesc = "Reset Cooldown", potImg = "https://www.tibiawiki.com.br/images/8/8c/Kooldown-Aid.gif"},
	{Name = "Strike Enhancement", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 120, alchemistExp = 100, alchemistLevel = 1, potionsClass = 1, potionDesc = "+5% Critical Rate", potImg = "https://www.tibiawiki.com.br/images/d/d5/Strike_Enhancement.gif"},
	{Name = "Stamina Extension", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 120, alchemistExp = 100, alchemistLevel = 4, potionsClass = 1, potionDesc = "+60 Minutes Stamina", potImg = "https://www.tibiawiki.com.br/images/a/ad/Stamina_Extension.gif"},
	{Name = "Charm Upgrade", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 120, alchemistExp = 100, alchemistLevel = 4, potionsClass = 1, potionDesc = "+5% Charm Hit Chance", potImg = "https://www.tibiawiki.com.br/images/9/96/Charm_Upgrade.gif"},
	{Name = "Wealth Duplex", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 120, alchemistExp = 100, alchemistLevel = 4, potionsClass = 1, potionDesc = "Double Loot", potImg = "https://www.tibiawiki.com.br/images/7/77/Wealth_Duplex.gif"},
	{Name = "Bestiary Betterment", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 1, potionDesc = "Double Charm Count", potImg = "https://www.tibiawiki.com.br/images/8/86/Bestiary_Betterment.gif"},

	{Name = "Fire Resilience", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 2, potionDesc = "+8% Fire Resistence", potImg = "https://www.tibiawiki.com.br/images/2/2a/Fire_Resilience.gif"},
	{Name = "Ice Resilience", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 2, potionDesc = "+8% Ice Resistence", potImg = "https://www.tibiawiki.com.br/images/6/63/Ice_Resilience.gif"},
	{Name = "Earth Resilience", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 2, potionDesc = "+8% Earth Resistence", potImg = "https://www.tibiawiki.com.br/images/5/50/Earth_Resilience.gif"},
	{Name = "Energy Resilience", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 2, potionDesc = "+8% Energy Resistence", potImg = "https://www.tibiawiki.com.br/images/8/86/Energy_Resilience.gif"},
	{Name = "Holy Resilience", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 2, potionDesc = "+8% Holy Resistence", potImg = "https://www.tibiawiki.com.br/images/e/ea/Holy_Resilience.gif"},
	{Name = "Death Resilience", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 2, potionDesc = "+8% Death Resistence", potImg = "https://www.tibiawiki.com.br/images/4/4e/Death_Resilience.gif"},
	{Name = "Physical Resilience", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 2, potionDesc = "+8% Physical Resistence", potImg = "https://www.tibiawiki.com.br/images/5/56/Physical_Resilience.gif"},

	{Name = "Fire Amplification", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 3, potionDesc = "+8% Fire Damage", potImg = "https://www.tibiawiki.com.br/images/8/80/Fire_Amplification.gif"},
	{Name = "Ice Amplification", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 3, potionDesc = "+8% Ice Damage", potImg = "https://www.tibiawiki.com.br/images/0/0b/Ice_Amplification.gif"},
	{Name = "Earth Amplification", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 3, potionDesc = "+8% Earth Damage", potImg = "https://www.tibiawiki.com.br/images/7/7e/Earth_Amplification.gif"},
	{Name = "Energy Amplification", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 3, potionDesc = "+8% Energy Damage", potImg = "https://www.tibiawiki.com.br/images/e/e5/Energy_Amplification.gif"},
	{Name = "Holy Amplification", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 3, potionDesc = "+8% Holy Damage", potImg = "https://www.tibiawiki.com.br/images/7/79/Holy_Amplification.gif"},
	{Name = "Death Amplification", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 3, potionDesc = "+8% Death Damage", potImg = "https://www.tibiawiki.com.br/images/5/5d/Death_Amplification.gif"},
	{Name = "Physical Amplification", potId = 0, itemNeed = {0, 0, 0}, itemQuantity = {0, 0, 0}, costGp = 0, questNeed = 0, questStorage = 0, storageId = 0, levelNeed = 0, alchemistExp = 100, alchemistLevel = 4, potionsClass = 3, potionDesc = "+8% Physical Damage", potImg = "https://www.tibiawiki.com.br/images/1/1d/Physical_Amplification.gif"}


}


return potionsTable