return {
	{ itemName= "avalanche rune", clientId = 3161, buy = 64 },
	{ itemName= "blank rune", clientId = 3147, buy = 10 },
	{ itemName= "chameleon rune", clientId = 3178, buy = 210 },
	{ itemName= "convince creature rune", clientId = 3177, buy = 80 },
	{ itemName= "cure poison rune", clientId = 3153, buy = 65 },
	{ itemName= "destroy field rune", clientId = 3148, buy = 15 },
	{ itemName= "energy field rune", clientId = 3164, buy = 38 },
	{ itemName= "energy wall rune", clientId = 3166, buy = 85 },
	{ itemName= "explosion rune", clientId = 3200, buy = 31 },
	{ itemName= "fire bomb rune", clientId = 3192, buy = 147 },
	{ itemName= "fire field rune", clientId = 3188, buy = 28 },
	{ itemName= "fire wall rune", clientId = 3190, buy = 61 },
	{ itemName= "great fireball rune", clientId = 3191, buy = 64 },
	{ itemName= "heavy magic missile rune", clientId = 3198, buy = 12 },
	{ itemName= "intense healing rune", clientId = 3152, buy = 95 },
	{ itemName= "light magic missile rune", clientId = 3174, buy = 4 },
	{ itemName= "poison field rune", clientId = 3172, buy = 21 },
	{ itemName= "poison wall rune", clientId = 3176, buy = 52 },
	{ itemName= "stalagmite rune", clientId = 3179, buy = 12 },
	{ itemName= "sudden death rune", clientId = 3155, buy = 162 },
	{ itemName= "ultimate healing rune", clientId = 3160, buy = 175 },
	{ itemName= "animate dead rune", clientId = 3203, buy = 375 },
	{ itemName= "desintegrate rune", clientId = 3197, buy = 26 },
	{ itemName= "energy bomb rune", clientId = 3149, buy = 203 },
	{ itemName= "fireball rune", clientId = 3189, buy = 30 },
	{ itemName= "icicle rune", clientId = 3158, buy = 30 },
	{ itemName= "magic wall rune", clientId = 3180, buy = 116 },
	{ itemName= "paralyze rune", clientId = 3165, buy = 700 },
	{ itemName= "poison bomb rune", clientId = 3173, buy = 85 },
	{ itemName= "soulfire rune", clientId = 3195, buy = 46 },
	{ itemName= "stone shower rune", clientId = 3175, buy = 41 },
	{ itemName= "thunderstorm rune", clientId = 3202, buy = 52 },
	{ itemName= "wild growth rune", clientId = 3156, buy = 160 },
	{ itemName= "empty potion flask", clientId = 283, sell = 5 },
	{ itemName= "empty potion flask", clientId = 284, sell = 5 },
	{ itemName= "empty potion flask", clientId = 285, sell = 5 },
	{ itemName= "great health potion", clientId = 239, buy = 225 },
	{ itemName= "great mana potion", clientId = 238, buy = 158 },
	{ itemName= "great spirit potion", clientId = 7642, buy = 254 },
	{ itemName= "health potion", clientId = 266, buy = 50 },
	{ itemName= "mana potion", clientId = 268, buy = 56 },
	{ itemName= "strong health potion", clientId = 236, buy = 115 },
	{ itemName= "strong mana potion", clientId = 237, buy = 108 },
	{ itemName= "supreme health potion", clientId = 23375, buy = 650 },
	{ itemName= "ultimate health potion", clientId = 7643, buy = 379 },
	{ itemName= "ultimate mana potion", clientId = 23373, buy = 488 },
	{ itemName= "ultimate spirit potion", clientId = 23374, buy = 488 },
	{ itemName= "vial", clientId = 2874, sell = 5 },
}